"""
English link stemming (like BibleWorks' "Use Link Stemming"): a search word is
expanded to every BLB word that shares a link head with it, so 'love' also
matches loved, loves, loving, beloved...

eng_links.tsv (word<TAB>head1,head2) is generated by tools/eng_links/build_links.py.
docs/data/eng_links.tsv is the same file for the static web build.
"""
import os

_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'eng_links.tsv')
_heads = None   # word -> [heads]
_forms = None   # head -> {words}


def _load():
    global _heads, _forms
    _heads, _forms = {}, {}
    with open(_PATH, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#'):     # credits header
                continue
            word, _, heads = line.rstrip('\n').partition('\t')
            hs = heads.split(',') if heads else [word]
            _heads[word] = hs
            for h in hs:
                _forms.setdefault(h, set()).add(word)


def expand(word):
    """All forms linked to `word` (lowercased, includes the word itself).
    Wildcard terms are returned unchanged -- stemming doesn't apply to them."""
    w = word.lower()
    if '*' in w or '?' in w:
        return [word]
    if _heads is None:
        _load()
    out = {w}
    for h in _heads.get(w, ()):
        out |= _forms.get(h, set())
    return sorted(out)
